export const allRoles = [
  //////  Mafia
  {
    id: 1,
    title: "رییس مافیا",
    side: "مافیا",
    img: "img/mafia/raiismafia.jpg",
  },
  { id: 2, title: "معشوقه", side: "مافیا", img: "img/mafia/mashooghe.jpg" },
  { id: 3, title: "روانکاو", side: "مافیا", img: "img/mafia/ravankav.jpg" },
  { id: 4, title: "محافظ ساده", side: "مافیا", img: "img/mafia/mohafez.jpg" },
  {
    id: 5,
    title: "محافظ ستاره دار",
    side: "مافیا",
    img: "img/mafia/mohafez.jpg",
  },
  { id: 6, title: "کابوس", side: "مافیا", img: "img/mafia/kaboos.jpg" },
  { id: 7, title: "جراح", side: "مافیا", img: "img/mafia/jarah.jpg" },
  { id: 8, title: "جلب", side: "مافیا", img: "img/mafia/jalab.jpg" },
  {
    id: 9,
    title: "قاتل حرفه ای",
    side: "مافیا",
    img: "img/mafia/ghateleherfeii.jpg",
  },
  { id: 11, title: "دو رو", side: "مافیا", img: "img/mafia/doroo.jpg" },
  { id: 12, title: "داروساز", side: "مافیا", img: "img/mafia/daroosaz.jpg" },
  {
    id: 13,
    title: "بمب ساز ساده",
    side: "مافیا",
    img: "img/mafia/bombsaz.jpg",
  },
  {
    id: 14,
    title: "بمب ساز ستاره دار",
    side: "مافیا",
    img: "img/mafia/bombsaz.jpg",
  },
  { id: 15, title: "آمپول زن", side: "مافیا", img: "img/mafia/ampoolzan.jpg" },
  { id: 16, title: "سیاه زخم", side: "مافیا", img: "img/mafia/siahzakhm.jpg" },
  { id: 17, title: "شارلاتان", side: "مافیا", img: "img/mafia/sharlatan.jpg" },
  {
    id: 18,
    title: "شاه کش ساده",
    side: "مافیا",
    img: "img/mafia/shahkosh.jpg",
  },
  {
    id: 19,
    title: "شاه کش ستاره دار",
    side: "مافیا",
    img: "img/mafia/shahkosh.jpg",
  },
  { id: 20, title: "شب خسب", side: "مافیا", img: "img/mafia/shabkhosb.jpg" },
  /////// Shahrvand
  {
    id: 21,
    title: "دکتر ساده",
    side: "شهروند",
    img: "img/shahrvand/doctor.jpg",
  },
  {
    id: 22,
    title: "دکتر ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/doctor.jpg",
  },
  {
    id: 23,
    title: "کارآگاه",
    side: "شهروند",
    img: "img/shahrvand/karagah.jpg",
  },
  {
    id: 24,
    title: "گورکن ساده",
    side: "شهروند",
    img: "img/shahrvand/goorkan.jpg",
  },
  {
    id: 25,
    title: "گورکن ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/goorkan.jpg",
  },
  {
    id: 26,
    title: "گورکن دو ستاره ",
    side: "شهروند",
    img: "img/shahrvand/goorkan.jpg",
  },
  { id: 27, title: "قاضی", side: "شهروند", img: "img/shahrvand/ghazi.jpg" },
  {
    id: 28,
    title: "قرنطینه چی",
    side: "شهروند",
    img: "img/shahrvand/gharantinechi.jpg",
  },
  {
    id: 29,
    title: "قهرمان ساده",
    side: "شهروند",
    img: "img/shahrvand/ghahreman.jpg",
  },
  {
    id: 30,
    title: "قهرمان ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/ghahreman.jpg",
  },
  {
    id: 31,
    title: "گردن کلفت",
    side: "شهروند",
    img: "img/shahrvand/gardankoloft.jpg",
  },
  {
    id: 32,
    title: "فرشته نجات",
    side: "شهروند",
    img: "img/shahrvand/fereshtenejat.jpg",
  },
  {
    id: 33,
    title: "فدایی ساده",
    side: "شهروند",
    img: "img/shahrvand/fadaii.jpg",
  },
  {
    id: 34,
    title: "فدایی ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/fadaii.jpg",
  },
  {
    id: 35,
    title: "افشاگر",
    side: "شهروند",
    img: "img/shahrvand/efshagar.jpg",
  },
  {
    id: 36,
    title: "دست کج ساده",
    side: "شهروند",
    img: "img/shahrvand/dastkaj.jpg",
  },
  {
    id: 37,
    title: "دست کج ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/dastkaj.jpg",
  },
  {
    id: 38,
    title: "دندان پزشک",
    side: "شهروند",
    img: "img/shahrvand/dandoonpezeshk.jpg",
  },
  { title: "افیون", side: "شهروند", img: "img/shahrvand/afyoon.jpg" },
  {
    id: 39,
    title: "پرستار",
    side: "شهروند",
    img: "img/shahrvand/parastar.jpg",
  },
  { id: 40, title: "نخبه", side: "شهروند", img: "img/shahrvand/nokhbe.jpg" },
  { id: 41, title: "نانوا", side: "شهروند", img: "img/shahrvand/nanva.jpg" },
  { id: 42, title: "ناقل", side: "شهروند", img: "img/shahrvand/naghel.jpg" },
  {
    id: 43,
    title: "کلانتر ساده",
    side: "شهروند",
    img: "img/shahrvand/kalantar.jpg",
  },
  {
    id: 44,
    title: "کلانتر ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/kalantar.jpg",
  },
  { id: 45, title: "جاسوس", side: "شهروند", img: "img/shahrvand/jasoos.jpg" },
  {
    id: 46,
    title: "جادوگر",
    side: "شهروند",
    img: "img/shahrvand/jadoogar.jpg",
  },
  { id: 47, title: "هوادار", side: "شهروند", img: "img/shahrvand/havadar.jpg" },
  { id: 48, title: "حنا", side: "شهروند", img: "img/shahrvand/hana.jpg" },
  {
    id: 49,
    title: "زندانبان",
    side: "شهروند",
    img: "img/shahrvand/zendanban.jpg",
  },
  { id: 50, title: "وکیل", side: "شهروند", img: "img/shahrvand/vakil.jpg" },
  {
    id: 51,
    title: "سیمین ساده",
    side: "شهروند",
    img: "img/shahrvand/simin.jpg",
  },
  {
    id: 52,
    title: "سیمین ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/simin.jpg",
  },
  {
    id: 53,
    title: "شکارچی ساده",
    side: "شهروند",
    img: "img/shahrvand/shekarchi.jpg",
  },
  {
    id: 54,
    title: "شکارچی ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/shekarchi.jpg",
  },
  {
    id: 55,
    title: "شهردار",
    side: "شهروند",
    img: "img/shahrvand/shahrdar.jpg",
  },
  { id: 56, title: "سپیدار", side: "شهروند", img: "img/shahrvand/sepidar.jpg" },
  { id: 57, title: "صبا", side: "شهروند", img: "img/shahrvand/saba.jpg" },
  { id: 58, title: "راوی", side: "شهروند", img: "img/shahrvand/ravi.jpg" },
  {
    id: 59,
    title: "پیوند ساده",
    side: "شهروند",
    img: "img/shahrvand/peyvand.jpg",
  },
  {
    id: 60,
    title: "پیوند ستاره دار",
    side: "شهروند",
    img: "img/shahrvand/peyvand.jpg",
  },
  {
    id: 61,
    title: "کارآگاه ویژه",
    side: "شهروند",
    img: "img/shahrvand/karagahvizhe.jpg",
  },
  ////////// Khakestari
  {
    id: 62,
    title: "همزاد ساده",
    side: "خاکستری",
    img: "img/khakestari/hamzad.jpg",
  },
  {
    id: 63,
    title: "همزاد ستاره دار",
    side: "خاکستری",
    img: "img/khakestari/hamzad.jpg",
  },
  {
    id: 64,
    title: "مجهول ساده",
    side: "خاکستری",
    img: "img/khakestari/majhool.jpg",
  },
  {
    id: 65,
    title: "مجهول ستاره دار",
    side: "خاکستری",
    img: "img/khakestari/majhool.jpg",
  },
  { id: 66, title: "مریض", side: "خاکستری", img: "img/khakestari/mariz.jpg" },
  ///////// Mostaghel
  {
    id: 67,
    title: "شیطان صفت",
    side: "مستقل",
    img: "img/mostaghel/sheytansefat.jpg",
  },
  { id: 68, title: "سندیکا", side: "مستقل", img: "img/mostaghel/sandika.jpg" },
  { id: 69, title: "ساغر", side: "مستقل", img: "img/mostaghel/saghar.jpg" },
  { id: 70, title: "نایب", side: "مستقل", img: "img/mostaghel/nayeb.jpg" },
  { id: 71, title: "جانی ساده", side: "مستقل", img: "img/mostaghel/jani.jpg" },
  {
    id: 72,
    title: "جانی ستاره دار",
    side: "مستقل",
    img: "img/mostaghel/jani.jpg",
  },
  {
    id: 73,
    title: "جانان ساده",
    side: "مستقل",
    img: "img/mostaghel/janan.jpg",
  },
  {
    id: 74,
    title: "جانان ستاره دار",
    side: "مستقل",
    img: "img/mostaghel/janan.jpg",
  },
  {
    id: 75,
    title: "گرگ نما",
    side: "مستقل",
    img: "img/mostaghel/gorgnama.jpg",
  },
  { id: 76, title: "عماد", side: "مستقل", img: "img/mostaghel/emad.jpg" },
  { id: 77, title: "دورگه", side: "مستقل", img: "img/mostaghel/dorage.jpg" },
  { id: 78, title: "کرونا", side: "مستقل", img: "img/mostaghel/corona.jpg" },
  {
    id: 79,
    title: "هزار چهره",
    side: "مستقل",
    img: "img/mostaghel/hezarchehre.jpg",
  },
];
